FROM node:20.13.1-alpine3.20

# 1. Set final working directory directly
WORKDIR /app/apps/single-sign-on

# 2. Copy and install deps first (Docker layer cache)
COPY apps/single-sign-on/package*.json ./
RUN npm install

# 3. Copy source
COPY apps/single-sign-on .

EXPOSE 5555

CMD ["npm", "run", "dev"]