FROM node:20.13.1-alpine3.20

WORKDIR /app/apps/websocket

# Copy and install deps (layer cache)
COPY apps/websocket/package*.json ./
RUN npm install

# Copy source
COPY apps/websocket .

EXPOSE 8083

CMD ["npm", "run", "dev"]