FROM node:20.13.1-slim

WORKDIR /app

COPY package*.json ./
COPY apps/lms-backend/package*.json ./apps/lms-backend/
COPY packages ./packages

RUN npm install


COPY apps/lms-backend ./apps/lms-backend

WORKDIR /app/apps/lms-backend

EXPOSE 8080

CMD ["sh", "-c", "npm run build --workspace=@repo/common && npm run dev --workspace=lms-backend"]