FROM node:20.13.1-alpine3.20
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

COPY apps/lms-backend/package.json ./apps/lms-backend/package.json

RUN npm ci --include=dev

COPY . .


EXPOSE 8080
CMD ["npm", "run", "dev"]
