FROM node:20.13.1-alpine3.20

WORKDIR /app/apps/lms-frontend

# Copy and install deps (layer cache)
COPY apps/lms-frontend/package*.json ./
RUN npm install

# Copy source
COPY apps/lms-frontend .

EXPOSE 3000

CMD ["npm", "run", "dev"]