FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

COPY apps/lms-frontend/package.json ./apps/lms-frontend/package.json

RUN npm ci --include=dev

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
