FROM node:20.13.1-slim

WORKDIR /app

ENV NODE_PATH=/app/apps/automation/node_modules

COPY package*.json ./

COPY apps/automation/package*.json ./apps/automation/

RUN npm install

COPY apps/automation ./apps/automation

WORKDIR /app/apps/automation

EXPOSE 8001

CMD ["npm", "run", "start:dev"]