FROM node:20.13.1-slim

WORKDIR /app

COPY package*.json ./

COPY apps/automation/package*.json ./apps/automation/

COPY packages ./packages

RUN npm install

COPY apps/automation ./apps/automation

WORKDIR /app/apps/automation

EXPOSE 8001

CMD ["npm", "run", "start:dev"]