import {
  BadgeCheck,
  BadgePlus,
  BookOpen,
  Building2,
  CalendarClock,
  ChartColumnBig,
  CircleCheck,
  ClipboardCheck,
  CopyPlus,
  FilePenLine,
  LogIn,
  LogOut,
  Megaphone,
  Palmtree,
  Power,
  Scale,
  Shield,
  Trash,
  Umbrella,
  UserCheck,
  UserCog,
} from "lucide-react";
import { IconConfig } from "./get-icon";

export const AUDIT_ICONS = {
  user_management: { icon: UserCog },
  user_attendance_management: { icon: UserCheck },
  attendance_report_management: { icon: ClipboardCheck },
  leave_report_management: { icon: ClipboardCheck },
  organization_setting_management: { icon: Building2 },
  organization_holiday_management: { icon: Umbrella },
  organization_event_management: { icon: Megaphone },
  role_management: { icon: Shield },
  leave_type_management: { icon: Palmtree },
  leave_request_management: { icon: CalendarClock },
  payroll_management: { icon: ChartColumnBig },

  read: { icon: BookOpen },
  create: { icon: BadgePlus },
  update: { icon: FilePenLine },
  activate: { icon: BadgeCheck },
  approve: { icon: CircleCheck },
  check_in: { icon: LogIn },
  check_out: { icon: LogOut },
  deactivate: { icon: Power },
  report: { icon: ChartColumnBig },
  create_bulk: { icon: CopyPlus },
  delete: { icon: Trash },
  sla: { icon: Scale },
} satisfies Record<string, IconConfig>;
